import sqlite3

conn = sqlite3.connect('locker.db')

c = conn.cursor()

data = [('Alicia Ng Yi-May', 'NULL'),
('An Fengyun', '1'),
('Ang Eng Choon', 'NULL'),
('Ang Peiyu', 'NULL'),
('Aow Ci Hui', 'NULL'),
('Asha Kirti Vora', '3'),
('Boh Wei Liang Brandon', 'NULL'),
('Bok Shung Hwee Grace', '6'),
('Chan Jia Kun Jason', 'NULL'),
('Chang Hui Hui Dorothy', 'NULL'),
('Chang Wan Yin', 'NULL'),
('Chen Huiqing Christine', 'NULL'),
('Chen Quansheng - Jason', 'NULL'),
('Chen Shunfa', '77'),
('Cheong Jin Hui Jillian', 'NULL'),
('Chew Geok Joo', '83'),
('Chew Kia Khang', 'NULL'),
('Chew Soon Chiang Martin', '19'),
('Chew Tah Lee', 'NULL'),
('Chew-Tan Bee Hong', 'NULL'),
('Chia Shu Hui', '36'),
('Chia Siew Ling', '14'),
('Chin Mee Yan Esther', '15'),
('Chin Shuang Ning', '45'),
('Chin Wei Ming', 'NULL'),
('Chong Kheng Wye', 'NULL'),
('Chong Hon Chung', 'NULL'),
('Cynthia Lim Ai Lian', 'NULL'),
('Deric Low', '11'),
('Emmanuel Pritish Andrew Sameer', '12'),
('Fang Chye Pin', '21'),
('Foo Thiam Sin Timothy', 'NULL'),
('Fu Yuanting Desiree', 'NULL'),
('Galistan Homer Shan', '18'),
('Geraldine Raphaela Joseph', 'NULL'),
('Gi Soong Chee', '23'),
('Goh Fenyu Jessica', 'NULL'),
('Goh Liangzhou', 'NULL'),
('Goh Wei Bin', '67'),
('Goh Wei Jie Jefferson', 'NULL'),
('Goh Wei Peng Belinda', 'NULL'),
('Han Yaohong Royston', '24'),
('Heng Li Tze - Joanna', 'NULL'),
('Ho Su Siew', 'NULL'),
('Ho Weng Lun', 'NULL'),
('Ho Xin An', 'NULL'),
('Hong Lan', '28'),
('Hong Shuqi', '26'),
('How Guan Ji Adrian', 'NULL'),
('Ilyana Hardianti bte Hartono W', '30'),
('Janet Long - Leong Foong Lin', 'NULL'),
('Jeffrey Ng Jie Li', '72'),
('Jiang Ling', 'NULL'),
('Joyce Teh Kiam Peng', 'NULL'),
('Juwana Bte Juwahir', '52'),
('Karuppiah Vinnarasi Celestyn', '40'),
('Kheng Hwee Teng', '35'),
('Khoo Geok Hwa', 'NULL'),
('Khow Zhi Wei Adrian', '2'),
('Koh Chin Poh', '48'),
('Lai Rouwen@Lai Ruiwen', '33'),
('Lam Non Har Serene', 'NULL'),
('Lau Min Yin Emmeline', 'NULL'),
('Lau Mui Choo Wendy', 'NULL'),
('Law Seow Li', 'NULL'),
('Lee Chee Keen', '47'),
('Lee Chin Sin', 'NULL'),
('Lee Joo Li Steven', '63'),
('Lee Kian Lam', '39'),
('Lee Seng Lee', 'NULL'),
('Lee Siew Choo', 'NULL'),
('Lee Wai Ching', '71'),
('Lee Wee Siang Joseph', '64'),
('Lee Wei Keong', 'NULL'),
('Lee Xiuli - Niki', '95'),
('Lee Yuet Meng Audrina', 'NULL'),
('Leo June Kit', 'NULL'),
('Leow Sock Cheng Pearly', 'NULL'),
('Lester Ian Lim Choong Siang', 'NULL'),
('Lew Wei Sern Vincent', 'NULL'),
('Lie Seok Hua', '53'),
('Lim Ai Juan Eileen', '54'),
('Lim Bee Kee - Mrs Tan', 'NULL'),
('Lim Boon Hwee', 'NULL'),
('Lim Boon Siong', 'NULL'),
('Lim Chiew Her', '56'),
('Lim Ee Lok Cassandra', 'NULL'),
('Lim Ern Chze - Angie', '80'),
('Lim Hwa Chuan', 'NULL'),
('Lim Hwee Teng', '8'),
('Lim Leong Hwee', 'NULL'),
('Lim Lian Joo - Jeremy', '59'),
('Lim Pia Leong', 'NULL'),
('Lim Yuan Chin', '62'),
('Lin Junkai', 'NULL'),
('Lin Le Ming', '31'),
('Loh Chien Yuen - June', 'NULL'),
('Loh Kok Sheng', 'NULL'),
('Loh Quee Yah', '9'),
('Loh Wan Fong - Sharlene', '42'),
('Loke Jee Wah', '55'),
('Low Chee Keong Timothy - Liu Zhiqiang', '90'),
('Low Boon Chu', 'NULL'),
('Low Siok Hong', '68'),
('Low Thiam Yew Alvin', '58'),
('Low Xin Tian', 'NULL'),
('Lu Han Lin', '70'),
('Mah Shi Hui - Adeline', '73'),
('Maryam Binte Mohamed Mokhtar', 'NULL'),
('Melvyn Tan Yeow Leng', 'NULL'),
('Mo Fengling', '78'),
('Neo Sock Khim', 'NULL'),
('Ng Bei Ling Vina', 'NULL'),
('Ng Boon Peng Benjamin', '61'),
('Ng Mui Leng', '75'),
('Ivan David Ng Qi Fan', '44'),
('Ng Shi Shi', '76'),
('Ng Si Yun Catherine', 'NULL'),
('Ng Wan Chin', 'NULL'),
('Ng Yu Jie', 'NULL'),
('Noorizan Beevi Binte Abdul Aziz', '32'),
('Noorshidah Bte Ismail', 'NULL'),
('Nora Bte Supaat', '57'),
('Norzian Bte Mohamed Yunos', 'NULL'),
('Norzahidah Bte Juhari', '41'),
('Nur Aisha Bte Jaini', '49'),
('Nurasyikin Binte Kassim', '4'),
('Nuurassyikin Binte Yusnan', '93'),
('Ong Chyai - Lian Grace', '84'),
('Ong Eldwen', 'NULL'),
('Ong Lay Pheng', '88'),
('Ong Pee Yeow', '85'),
('Ong Wei Xiang Adrian', '13'),
('Ong Wen Kai', 'NULL'),
('Ooi Ming Fong James', 'NULL'),
('Pamela Kuppusamy Samales', '27'),
('Pang Hai Chet', '86'),
('Pear Siew Lee', 'NULL'),
('Phua - Loo Poh Lim', 'NULL'),
('Poh Pei Hsia Debbie', '22'),
('Rathiy Devi d/o Ramanathan', 'NULL'),
('Renata Priscilla Winata', 'NULL'),
('Ronson Neo Boon Kiat', 'NULL'),
('Sangeetha Gangadharan', '94'), 
('Sau Wee Wee', 'NULL'),
('Seah Hui Ting Nathalie - Mrs Tan', '74'),
('Seah Puay Hoon Eleanor - Mrs Goh', 'NULL'),
('Seet Seok Beng Stella', 'NULL'),
('See - Toh Pei Ling', 'NULL'),
('Selena Vera Hey', '38'),
('Seng Sze Ming - Sia - Daniel', '16'),
('Sherene Jeevitha Joseph', 'NULL'),
('Shi Mengchen', 'NULL'),
('Sim Hoon Kuan', 'NULL'),
('Sim Yan Jun', 'NULL'),
('Sim Yin Hui', 'NULL'),
('Siti Shafaa Bte Yang Razali', '34'),
('Siti Zakia Binte Zainol', '81'),
('Sng Jianming - Joshua', '51'),
('Soh Wen Qi Rachel', '29'),
('Tan Ai Ling Debbie', 'NULL'),
('Tan Chee Keong Matthew', 'NULL'),
('Tan Chien Huah - Peter', 'NULL'),
('Tan Chien Ming', 'NULL'),
('Tan Chin Hui - Alan', '98'),
('Tan Chor Kheng - Christine', '99'),
('Tan Chwee Bock', 'NULL'),
('Tan De Lun Eugene', 'NULL'),
('Tan Hee Ming', 'NULL'),
('Tan Ing Keat', '97'),
('Tan Jia Yi Joel', 'NULL'),
('Tan Jiaqi', 'NULL'),
('Tan Kae Ling', 'NULL'),
('Tan Lee Hwee', 'NULL'),
('Tan Leong Howe', 'NULL'),
('Tan Mei Qiang', 'NULL'),
('Tan Siu Yian Jerena - Mrs Su ', '25'),
('Tan Swee Leng', 'NULL'),
('Tan Tui Gee', 'NULL'),
('Tan Yu Shi', '5'),
('Tang Yin Chee Richard - Mdm Lim Ling Ling', 'NULL'),
('Tang Wai Keen - Joyce', '79'),
('Tang Yew Seng', 'NULL'),
('Tay Teow Kiat', 'NULL'),
('Teo Chai Hock', '66'),
('Teo Geok Hiok', 'NULL'),
('Teo Joo Cheong', 'NULL'),
('Teo Yan Ni Linda', '89'),
('Teoh Ai Keong', 'NULL'),
('Terence Khee Jun Xian', 'NULL'),
('Tiah Junkai', 'NULL'),
('Tong Siok Mei', 'NULL'),
('Vaz Cecilia Anne Angela', '82'),
('Wang Yanchun', 'NULL'),
('Wee Hock Guan', '7'),
('Wong Lu Ting', '60'),
('Wong Min Tzu Sharilyn', '50'),
('Wong Ting Ee', 'NULL'),
('Yang Chien Hwa', '20'),
('Yang Yunhui - Faith', '69'),
('Yap Chang Xin Daryl', '96'),
('Yap Kian Eng - Michael', 'NULL'),
('Yap Kok Hung', 'NULL'),
('Ye Meixiu', '10'),
('Yeo Cheng Kok', '92'),
('Yeo Kim Neo Michelle', 'NULL'),
('Yeo Meng Han', 'NULL'),
('Yick Jue Ru', 'NULL'),
('Yip Sook Kwan', 'NULL'),
('Zarifah Binte Zainal', '46'),
('Zhang Liping', '17'),
('Zhang Weidong', 'NULL'),
('Zhao Bolun Ian', 'NULL'),
('Diana Loi', 'NULL'),
('Jessie Yeoh', 'NULL'),
('Ho Li-En', 'NULL'),
('Patricia Koh Seok Kwan', 'NULL')]

c.executemany('INSERT INTO locker_data VALUES (?,?)', data)

conn.commit()
